import { PayloadAction, createAsyncThunk, createSlice } from "@reduxjs/toolkit";

interface CounterState {
  value: number;
}

const initialState: CounterState = {
  value: 0,
};

const counterSlice = createSlice({
  name: "counter",
  initialState,
  reducers: {
    //behind the scenes coppies the state and returns a new state
    // only works with createSlice from redux toolkit
    increment: (state) => {
      state.value += 1;
    },
    decrement: (state) => {
      state.value -= 1;
    },
    incrementByAmount: (state, action: PayloadAction<number>) => {
      state.value += action.payload;
    },
  },

  extraReducers: (builder) => {
    builder
      .addCase(incrementAsync.pending, () => {
        //sym for loading state
        console.log("loading state");
      })
      .addCase(
        incrementAsync.fulfilled,
        (state, action: PayloadAction<number>) => {
          state.value += action.payload;
        }
      );
  },
});

export const incrementAsync = createAsyncThunk(
  "counter/incrementAsync",
  async (amount: number) => {
    //sym for async operations like fetching data from an API
    await new Promise((resolve) => setTimeout(resolve, 1000));
    return amount;
  }
);

// we automatically get actions generated by createSlice
export const { increment, decrement, incrementByAmount } = counterSlice.actions;
// we automatically get a reducer generated by createSlice
export default counterSlice.reducer;
